### ISSUE TITLE
Unhandled exception. System.Exception: Failed to find codecopy

### ISSUE THREAD

**Issue by elizabethdinella** [SoftSec-KAIST/Smartian#4]
Hello, 

Analyzing the attached file is raising a `Failed to codecopy` Exception. 
Compiled with solc version 0.8.1

[OkayMutantBears.txt](https://github.com/SoftSec-KAIST/Smartian/files/8713034/OkayMutantBears.txt)

```
[00:00:00:00] Fuzz target : ../BabaZ/build/BabaZ.bin
[00:00:00:00] Fuzzing starts at 09:24:47
[00:00:00:00] Time limit : 120 s
Unhandled exception. System.Exception: Failed to find codecopy
   at B2R2.MiddleEnd.Reclaimer.EVMCodeCopyAnalysis.findCodeCopyOffset(BinHandle hdl, BinaryPointer bp, FSharpList`1 pushList) in /mnt/c/Workspace/Smartian/EVMAnalysis/B2R2/src/MiddleEnd/Reclaimer/EVMCodeCop
   at B2R2.MiddleEnd.Reclaimer.EVMCodeCopyAnalysis.recoverCopiedCode(BinEssence ess) in /mnt/c/Workspace/Smartian/EVMAnalysis/B2R2/src/MiddleEnd/Reclaimer/EVMCodeCopyAnalysis.fs:line 64
   at B2R2.MiddleEnd.Reclaimer.EVMCodeCopyAnalysis.B2R2.MiddleEnd.Reclaimer.IAnalysis.Run(BinEssence ess, AnalysisHint hint) in /mnt/c/Workspace/Smartian/EVMAnalysis/B2R2/src/MiddleEnd/Reclaimer/EVMCodeCopy
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at B2R2.MiddleEnd.Reclaimer.Reclaimer.run(FSharpList`1 analyses, BinEssence ess) in /mnt/c/Workspace/Smartian/EVMAnalysis/B2R2/src/MiddleEnd/Reclaimer/Reclaimer.fs:line 32
   at EVMAnalysis.Parse.run(String binFile, String abiFile) in /Users/elizabethdinella/projects/smart-contracts/Smartian/EVMAnalysis/src/FrontEnd/Parse.fs:line 65
   at EVMAnalysis.TopLevel.parseOnly(String binFile, String abiFile) in /Users/elizabethdinella/projects/smart-contracts/Smartian/EVMAnalysis/src/Analysis/TopLevel.fs:line 91
   at Smartian.Fuzz.initializeWithoutDFA(FuzzOption opt) in /Users/elizabethdinella/projects/smart-contracts/Smartian/src/Fuzz/Fuzz.fs:line 27
   at Smartian.Fuzz.run[a](String[] args) in /Users/elizabethdinella/projects/smart-contracts/Smartian/src/Fuzz/Fuzz.fs:line 145
   at Smartian.Main.runMode(String mode, String[] optArgs) in /Users/elizabethdinella/projects/smart-contracts/Smartian/src/Main/Main.fs:line 14
   at Smartian.Main.main(String[] args) in /Users/elizabethdinella/projects/smart-contracts/Smartian/src/Main/Main.fs:line 22
Abort trap: 6
```

**Comment by jchoi2022** [comment]
Thank you for the report! I will investigate this when I have some time (may not be possible in this month, sorry in advance).

**Comment by faustocarva** [comment]
Is this bug due to the solc version and bytecode generated for more recent versions?
